import { getTranslations } from "next-intl/server";
import { AppShell } from "@/components/AppShell";

type Props = {
  params: Promise<{ locale: string }>;
};

export async function generateMetadata({ params }: Props) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "legal" });
  return { title: `${t("termsTitle")} — Unfolda` };
}

const sectionStyle = {
  marginBottom: "2rem",
};

const h2Style = {
  fontSize: "1.125rem",
  fontWeight: 600,
  marginBottom: "0.75rem",
  color: "var(--color-navy)",
};

const pStyle = {
  fontSize: "0.9375rem",
  lineHeight: "1.75",
  color: "var(--color-navy)",
  opacity: 0.8,
  marginBottom: "0.75rem",
};

const liStyle = {
  fontSize: "0.9375rem",
  lineHeight: "1.75",
  color: "var(--color-navy)",
  opacity: 0.8,
  marginBottom: "0.375rem",
};

export default async function TermsPage({ params }: Props) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "legal" });

  return (
    <AppShell>
      <article
        className="mx-auto max-w-2xl py-12"
        style={{ color: "var(--color-navy)" }}
      >
        <header style={{ marginBottom: "2.5rem" }}>
          <h1
            className="font-heading text-3xl"
            style={{ marginBottom: "0.5rem", color: "var(--color-navy)" }}
          >
            {t("termsTitle")}
          </h1>
          <p style={{ fontSize: "0.875rem", opacity: 0.5, marginBottom: "0.25rem" }}>
            {t("lastUpdated")}
          </p>
          <p style={{ fontSize: "0.875rem", opacity: 0.5 }}>{t("bindingNote")}</p>
        </header>

        <section style={sectionStyle}>
          <h2 style={h2Style}>1. Service Description</h2>
          <p style={pStyle}>
            Unfolda (&ldquo;the Service&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is an AI-assisted
            EPUB translation platform. We process electronic books uploaded by users using large language
            models (LLMs) provided by Anthropic, and return a translated or annotated edition in EPUB format.
          </p>
          <p style={pStyle}>
            The Service is provided on an as-is basis. Translation output is generated by AI and may contain
            errors, omissions, or inaccuracies. We do not guarantee the accuracy, completeness, or suitability
            of any translation for any particular purpose.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>2. User Accounts</h2>
          <p style={pStyle}>
            Access to the Service requires authentication via Google OAuth. By creating an account you agree
            to provide accurate information and to keep your credentials secure. You are responsible for all
            activity that occurs under your account.
          </p>
          <p style={pStyle}>
            We reserve the right to suspend or terminate accounts that violate these Terms or are used for
            abusive, fraudulent, or unlawful purposes.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>3. User Content and Copyright</h2>
          <p style={pStyle}>
            You retain all intellectual property rights in the files you upload (&ldquo;User Content&rdquo;).
            By uploading a file you grant Unfolda a limited, non-exclusive, royalty-free licence to process,
            store, and transform the file solely for the purpose of providing the translation service to you.
          </p>
          <p style={pStyle}>
            <strong>You warrant that you have the legal right to upload and process the source file.</strong>{" "}
            This includes owning the copyright, holding a valid licence that permits derivative works, or the
            work being in the public domain. We do not verify copyright status of uploaded content. You are
            solely responsible for ensuring your use of the Service does not infringe third-party rights.
          </p>
          <p style={pStyle}>
            We do not claim ownership of any User Content or translation output.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>4. Data Retention</h2>
          <p style={pStyle}>
            Uploaded source files and translated output files are stored for a retention period of
            30 days (&ldquo;Retention Window&rdquo;) from the date of submission. After this period,
            files are automatically and permanently deleted from our systems.
          </p>
          <p style={pStyle}>
            We do not guarantee availability of files beyond the Retention Window. You are responsible
            for downloading your translated output before it expires. The expiry date is displayed on
            the job status page.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>5. Credits System</h2>
          <p style={pStyle}>
            Certain features of the Service require credits, a consumable virtual currency associated
            with your account. Credits are consumed when translation jobs are processed. The credit cost
            depends on the word count of the source material, the translation mode, and the selected
            quality tier.
          </p>
          <ul style={{ paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>
            <li style={liStyle}>Credits are non-transferable between accounts.</li>
            <li style={liStyle}>Unused credits have no cash value and are not refundable except as required by applicable law.</li>
            <li style={liStyle}>We reserve the right to adjust credit pricing with reasonable notice.</li>
            <li style={liStyle}>Credits may be granted, adjusted, or revoked at our discretion for service-related reasons.</li>
          </ul>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>6. Prohibited Uses</h2>
          <p style={pStyle}>You agree not to use the Service to:</p>
          <ul style={{ paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>
            <li style={liStyle}>Upload content that infringes the intellectual property rights of others.</li>
            <li style={liStyle}>Process illegal, defamatory, harmful, or otherwise objectionable content.</li>
            <li style={liStyle}>Attempt to reverse-engineer, scrape, or abuse the Service infrastructure.</li>
            <li style={liStyle}>Circumvent usage limits, credit checks, or access controls.</li>
            <li style={liStyle}>Use the Service for any purpose that violates applicable laws or regulations.</li>
          </ul>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>7. Disclaimer of Warranties</h2>
          <p style={pStyle}>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTY
            OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not warrant that the Service
            will be uninterrupted, error-free, or that translation output will meet your requirements.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>8. Limitation of Liability</h2>
          <p style={pStyle}>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, UNFOLDA SHALL NOT BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, LOSS OF
            PROFITS, OR LOSS OF BUSINESS, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE,
            EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p style={pStyle}>
            Our total liability for any claim arising out of or relating to these Terms or the Service
            shall not exceed the amount you paid us in the twelve months preceding the claim, or €10,
            whichever is greater.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>9. Changes to These Terms</h2>
          <p style={pStyle}>
            We may update these Terms from time to time. We will notify users of material changes by
            updating the &ldquo;Last updated&rdquo; date at the top of this page. Your continued use of
            the Service after changes are posted constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>10. Governing Law</h2>
          <p style={pStyle}>
            These Terms are governed by and construed in accordance with applicable law. Any disputes
            arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>11. Contact</h2>
          <p style={pStyle}>
            If you have questions about these Terms, please contact us through the support channel listed
            in your account settings.
          </p>
        </section>
      </article>
    </AppShell>
  );
}
