"""EPUB reconstruction engine for the export stage.

Single public function: build_epub(formatted, source_bytes, config) -> bytes

Approach:
- Load the original EPUB using ebooklib to preserve all non-content items
  (images, fonts, NCX, navigation document, OPF metadata, etc.)
- Create a single external stylesheet (unfolda.css) and add it to the manifest
- Replace the body content of each spine document item with formatted blocks,
  linking to unfolda.css via a relative <link rel="stylesheet"> in <head>
- Prepend a disclaimer page as the FIRST spine item
- Update OPF metadata (title, language, description)
- Serialize to bytes

CSS is written as an EpubItem so it appears in the OPF manifest and is
accessible to all EPUB reading systems.  Inline <style> blocks are NOT used
because ebooklib reconstructs <head> from EpubHtml object metadata on
round-trip, silently discarding any <style> content set via set_content().

No LLM calls. No external I/O. Deterministic.
"""
from __future__ import annotations

import html
import io
import posixpath
import uuid
from typing import Dict, List, Optional

from app.pipeline.export.models import ExportConfig, ExportError
from app.pipeline.formatting.models import FormattedBlock, FormattedDocument

# ── Stylesheet ────────────────────────────────────────────────────────────────

_CSS_FILE_NAME = "unfolda.css"

# Single stylesheet shared by all Unfolda-generated pages (docs/BRAND.md).
_STYLESHEET = """/* Unfolda AI reading edition — docs/BRAND.md */
body { font-family: 'Georgia', serif; color: #1a1f36; }

/* Paragraph group container */
.unfolda-block { margin-bottom: 0; }
.unfolda-hr { border: none; border-top: 1px solid #e0dcd4; margin: 1.6em 0; }

/* Section labels: ORIGINAL / TRANSLATION / NOTES / ORIGINAL (REPEAT) */
.block-label {
  display: block;
  font-size: 0.7em;
  letter-spacing: 0.1em;
  color: #999;
  text-transform: uppercase;
  margin-bottom: 0.3em;
}

/* Text sections */
.original { color: #1a1f36; margin: 0 0 0.8em 0; }
.translation { color: #1a1f36; margin: 0 0 0.8em 0; }
.original-repeat { color: #1a1f36; margin: 0; font-size: 0.95em; }

/* Notes block */
.explanations { border-left: 3px solid #e8a849; padding: 0.4em 0.6em; margin: 0 0 0.8em 0; }
.explanation { font-size: 0.88em; color: #555; font-style: italic; margin: 0.2em 0; }

/* Disclaimer page */
.disclaimer { max-width: 480px; margin: 3em auto; border: 1px solid #e0dcd4; padding: 2em; }
.disclaimer h2 { color: #1a1f36; margin-top: 0; }
.disclaimer p { line-height: 1.6; }
.disclaimer-label { font-weight: bold; color: #1a1f36; }"""

# ── XHTML template ────────────────────────────────────────────────────────────

# {css_href} is a relative path from the chapter file to unfolda.css,
# computed per-chapter by _css_href().
_XHTML_TEMPLATE = """\
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{lang}">
<head>
  <meta charset="utf-8"/>
  <title>{title}</title>
  <link rel="stylesheet" type="text/css" href="{css_href}"/>
</head>
<body>
{body}
</body>
</html>"""

_MODE_LABELS = {"translate": "Translate", "guided": "Guided"}

# ── Localized block labels and disclaimer text ────────────────────────────────

# Keys: original, translation, notes, original_repeat
_BLOCK_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "original":        "Original",
        "translation":     "Translation",
        "notes":           "Notes",
        "original_repeat": "Original (repeat)",
    },
    "ru": {
        "original":        "Оригинал",
        "translation":     "Перевод",
        "notes":           "Примечания",
        "original_repeat": "Оригинал (повтор)",
    },
    "sr": {
        "original":        "Original",
        "translation":     "Prevod",
        "notes":           "Napomene",
        "original_repeat": "Original (ponavljanje)",
    },
}

_DISCLAIMER_TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "heading":     "Unfolda \u2014 AI Translation Notice",
        "generated":   "was generated by Unfolda, an AI-powered reading and language learning tool.",
        "mode_label":  "Mode",
        "lang_label":  "Target language",
        "footer":      (
            "This content is for personal language learning only. "
            "All original rights remain with the copyright holder. "
            "The translation is AI-generated and may contain errors."
        ),
    },
    "ru": {
        "heading":     "Unfolda \u2014 Уведомление об ИИ-переводе",
        "generated":   "было создано сервисом Unfolda — инструментом для чтения и изучения языков на основе ИИ.",
        "mode_label":  "Режим",
        "lang_label":  "Целевой язык",
        "footer":      (
            "Данный материал предназначен исключительно для личного изучения языка. "
            "Все права на оригинальное произведение принадлежат правообладателю. "
            "Перевод создан с помощью ИИ и может содержать ошибки."
        ),
    },
    "sr": {
        "heading":     "Unfolda \u2014 Obaveštenje o AI prevodu",
        "generated":   "je generisano od strane servisa Unfolda, alata za čitanje i učenje jezika koji koristi veštačku inteligenciju.",
        "mode_label":  "Način",
        "lang_label":  "Ciljni jezik",
        "footer":      (
            "Ovaj sadržaj je namenjen isključivo za lično učenje jezika. "
            "Sva originalna prava ostaju vlasništvo nosioca autorskih prava. "
            "Prevod je generisan pomoću veštačke inteligencije i može sadržati greške."
        ),
    },
}

def _get_block_labels(target_language: str) -> dict[str, str]:
    """Return localized block labels, falling back to English."""
    return _BLOCK_LABELS.get(target_language, _BLOCK_LABELS["en"])


def _get_disclaimer_text(target_language: str) -> dict[str, str]:
    """Return localized disclaimer strings, falling back to English."""
    return _DISCLAIMER_TEXTS.get(target_language, _DISCLAIMER_TEXTS["en"])


def build_epub(
    formatted: FormattedDocument,
    source_epub_bytes: bytes,
    config: ExportConfig,
) -> bytes:
    """Reconstruct an EPUB from a FormattedDocument and the original EPUB bytes.

    Args:
        formatted:         Output of the formatting stage.
        source_epub_bytes: Raw bytes of the original EPUB from object storage.
        config:            Export configuration (mode, target language, metadata).

    Returns:
        Bytes of the reconstructed EPUB file.

    Raises:
        ExportError: If the source EPUB cannot be parsed or writing fails.
    """
    try:
        import ebooklib
        from ebooklib import epub as eblib
    except ImportError as exc:
        raise ExportError(f"ebooklib not available: {exc}") from exc

    try:
        book = eblib.read_epub(io.BytesIO(source_epub_bytes), options={"ignore_ncx": False})
    except Exception as exc:
        raise ExportError(f"Failed to parse source EPUB: {exc}") from exc

    # Register the Unfolda stylesheet in the manifest.
    css_item = _build_css_item(eblib)
    book.add_item(css_item)

    # Group blocks by chapter_ref for efficient lookup.
    blocks_by_chapter: Dict[str, List[FormattedBlock]] = {}
    for block in formatted.formatted_blocks:
        blocks_by_chapter.setdefault(block.chapter_ref, []).append(block)

    # Replace content of each spine document item that has blocks.
    # ebooklib reconstructs <head> from item attributes on round-trip and
    # discards any <head> content set via set_content().  We therefore:
    #   1. Pass only the <body> fragment to set_content().
    #   2. Set item.title / item.lang via item attributes.
    #   3. Register the CSS link via item.add_link() so ebooklib writes it
    #      into <head> during serialisation.
    for item in book.get_items_of_type(ebooklib.ITEM_DOCUMENT):
        blocks = blocks_by_chapter.get(item.id)
        if not blocks:
            continue
        chapter_title = _extract_item_title(item)
        body_html = _build_chapter_body(
            blocks=blocks,
            mode=formatted.mode,
            target_language=config.target_language,
        )
        item.set_content(body_html.encode("utf-8"))
        item.title = chapter_title
        item.lang = config.target_language
        # Add the stylesheet link via ebooklib's API so it survives head
        # reconstruction.  Remove any prior unfolda link to avoid duplicates
        # (e.g., when build_epub is called twice on the same item object).
        item.links = [
            lnk for lnk in getattr(item, "links", [])
            if lnk.get("href", "").find("unfolda") == -1
        ]
        item.add_link(
            href=_css_href(item.file_name),
            rel="stylesheet",
            type="text/css",
        )

    # Update OPF metadata.
    _update_metadata(book, config)

    # Prepend disclaimer page so it appears before chapter 1.
    disclaimer = _build_disclaimer_item(config, eblib)
    book.add_item(disclaimer)
    book.spine = [disclaimer] + list(book.spine)

    # When a book is round-tripped (read then write), ebooklib sets book.toc
    # to a flat list of Link objects. write_epub expects tuples (section, children).
    # Clear the toc to avoid NCX write errors — navigation doc (EpubNav) is preserved.
    book.toc = ()

    try:
        buf = io.BytesIO()
        eblib.write_epub(buf, book, {})
        return buf.getvalue()
    except Exception as exc:
        raise ExportError(f"Failed to write output EPUB: {exc}") from exc


# ── Internal helpers ──────────────────────────────────────────────────────────


def _build_css_item(eblib):
    """Build the EpubItem for the Unfolda stylesheet."""
    return eblib.EpubItem(
        uid="unfolda-css",
        file_name=_CSS_FILE_NAME,
        media_type="text/css",
        content=_STYLESHEET.encode("utf-8"),
    )


def _css_href(chapter_file_name: str) -> str:
    """Return the href for the Unfolda stylesheet relative to a chapter file.

    Examples:
        chapter at "Text/ch01.xhtml"     -> "../unfolda.css"
        chapter at "ch01.xhtml"          -> "unfolda.css"
        chapter at "EPUB/Text/ch.xhtml"  -> "../../unfolda.css"
    """
    chapter_dir = posixpath.dirname(chapter_file_name) or "."
    return posixpath.relpath(_CSS_FILE_NAME, chapter_dir)


def _update_metadata(book, config: ExportConfig) -> None:
    """Replace title, language, and description in the book's OPF metadata."""
    # ebooklib stores DC metadata under the full namespace URI, not the "DC" alias.
    _DC_URI = "http://purl.org/dc/elements/1.1/"

    mode_label = _MODE_LABELS.get(config.mode, config.mode.capitalize())
    lang_upper = config.target_language.upper()
    new_title = f"{config.source_title} — {mode_label}, {lang_upper}"
    description = (
        f"AI-translated edition of '{config.source_title}' by {config.source_author}. "
        f"Mode: {mode_label}. Target language: {lang_upper}. "
        "Generated by Unfolda. For personal language learning only."
    )

    dc = book.metadata.setdefault(_DC_URI, {})
    dc["title"] = [(new_title, {})]
    dc["language"] = [(config.target_language, {})]
    dc["description"] = [(description, {})]


def _build_chapter_body(
    blocks: List[FormattedBlock],
    mode: str,
    target_language: str = "en",
) -> str:
    """Return the <body> fragment for a chapter (no surrounding <html>/<head>).

    ebooklib's EpubHtml.set_content() stores body content only; the full
    document is reconstructed from item attributes during serialisation.

    Paragraph groups are separated by a subtle <hr> so each block is visually
    distinct without relying on heavy bottom-margin spacing.
    """
    labels = _get_block_labels(target_language)
    parts: List[str] = []
    for block in blocks:
        parts.append(_build_block_html(block, mode, labels))
    if mode == "guided":
        hr = '<hr class="unfolda-hr"/>'
        return f"\n{hr}\n".join(parts)
    return "\n".join(parts)


def _normalize_text(text: str) -> str:
    """Collapse excess whitespace/newlines in text before HTML rendering."""
    import re as _re
    return _re.sub(r"\s+", " ", text).strip()


def _build_block_html(block: FormattedBlock, mode: str, labels: Optional[dict] = None) -> str:
    """Generate the HTML fragment for one FormattedBlock.

    Translate mode: labelled translation paragraph only.
    Guided mode:    ORIGINAL → TRANSLATION → NOTES (optional).
                    No repeated original — the structure is: read the original,
                    read the translation, read the notes.  The original_repeat
                    field is intentionally omitted here to avoid content
                    duplication in the output EPUB.
    """
    if labels is None:
        labels = _BLOCK_LABELS["en"]

    translation = _normalize_text(block.translation)
    t = html.escape(translation)

    if mode == "guided":
        original = _normalize_text(block.original)
        o = html.escape(original)

        expl_html = ""
        if block.explanations:
            # Flatten: split any multi-line item so each note gets its own <p>.
            note_items = [
                line
                for n in block.explanations
                for line in (ln.strip() for ln in n.splitlines())
                if line
            ]
            if note_items:
                notes = "".join(
                    f'    <p class="explanation">{html.escape(n)}</p>\n'
                    for n in note_items
                )
                expl_html = (
                    f'  <span class="block-label">{html.escape(labels["notes"])}</span>\n'
                    f'  <div class="explanations">\n{notes}  </div>\n'
                )

        return (
            f'<div class="unfolda-block guided">\n'
            f'  <span class="block-label">{html.escape(labels["original"])}</span>\n'
            f'  <p class="original">{o}</p>\n'
            f'  <span class="block-label">{html.escape(labels["translation"])}</span>\n'
            f'  <p class="translation">{t}</p>\n'
            f'{expl_html}'
            f'</div>'
        )
    else:
        return (
            f'<div class="unfolda-block">\n'
            f'  <p class="translation">{t}</p>\n'
            f'</div>'
        )

def _build_disclaimer_item(config: ExportConfig, eblib):
    """Build the disclaimer EpubHtml item (appended to spine)."""
    mode_label = _MODE_LABELS.get(config.mode, config.mode.capitalize())
    lang_upper = config.target_language.upper()
    d = _get_disclaimer_text(config.target_language)
    body = (
        '<div class="disclaimer">\n'
        f'  <h2>{html.escape(d["heading"])}</h2>\n'
        f'  <p>&#171;<em>{html.escape(config.source_title)}</em>&#187; '
        f'{html.escape(config.source_author)} — {html.escape(d["generated"])}</p>\n'
        f'  <p><span class="disclaimer-label">{html.escape(d["mode_label"])}:</span> {html.escape(mode_label)}</p>\n'
        f'  <p><span class="disclaimer-label">{html.escape(d["lang_label"])}:</span> {html.escape(lang_upper)}</p>\n'
        f'  <p>{html.escape(d["footer"])}</p>\n'
        f'</div>'
    )
    disclaimer_file_name = "unfolda_disclaimer.xhtml"
    content = _XHTML_TEMPLATE.format(
        lang=html.escape(config.target_language),
        title="Disclaimer",
        css_href=_css_href(disclaimer_file_name),
        body=body,
    )
    item = eblib.EpubHtml(
        uid=f"unfolda-disclaimer-{uuid.uuid4().hex[:8]}",
        file_name=disclaimer_file_name,
        lang=config.target_language,
    )
    item.set_content(content.encode("utf-8"))
    return item


def _extract_item_title(item) -> str:
    """Best-effort chapter title from the EPUB item title attribute."""
    try:
        if hasattr(item, "title") and item.title:
            return str(item.title)
    except Exception:
        pass
    return "Chapter"
